openapi: 3.0.0
info:
  title: JIRA Tool API
  version: 1.0.0
  description: API for a JIRA Tool

paths:
  /api/v1/auth/login/:
    post:
      tags:
        - Authentication
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login

  /api/v1/auth/signup/:
    post:
      tags:
        - Authentication
      summary: User registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
      responses:
        '201':
          description: User created

  /api/v1/auth/logout/:
    post:
      tags:
        - Authentication
      summary: User logout
      responses:
        '200':
          description: Successful logout

  /api/v1/auth/user/:
    get:
      tags:
        - Authentication
      summary: Get authenticated user details
      responses:
        '200':
          description: Authenticated user details

  /api/v1/projects/:
    get:
      tags:
        - projects
      summary: Get all projects
      responses:
        '200':
          description: List of projects
    post:
      tags:
        - projects
      summary: Create a new project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                start_date:
                  type: string
                  format: date
                end_date:
                  type: string
                  format: date
      responses:
        '201':
          description: Project created

  /api/v1/projects/{projectId}/:
    get:
      tags:
        - projects
      summary: Get project details
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Project details
    put:
      tags:
        - projects
      summary: Update a project
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                start_date:
                  type: string
                  format: date
                end_date:
                  type: string
                  format: date
      responses:
        '200':
          description: Project updated
    delete:
      tags:
        - projects
      summary: Delete a project
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Project deleted

  /api/v1/projects/{projectId}/tasks/:
    get:
      tags:
        - tasks
      summary: Get all tasks for a project
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of tasks
    post:
      tags:
        - tasks
      summary: Create a new task
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                status:
                  type: string
                priority:
                  type: string
                deadline:
                  type: string
                  format: date
                assigned_to:
                  type: string
      responses:
        '201':
          description: Task created

  /api/v1/projects/{projectId}/tasks/{taskId}/:
    get:
      tags:
        - tasks
      summary: Get task details
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task details
    put:
      tags:
        - tasks
      summary: Update a task
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                status:
                  type: string
                priority:
                  type: string
                deadline:
                  type: string
                  format: date
                assigned_to:
                  type: string
      responses:
        '200':
          description: Task updated
    delete:
      tags:
        - tasks
      summary: Delete a task
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Task deleted

  /api/v1/projects/{projectId}/tasks/{taskId}/comments/:
    get:
      tags:
        - comments
      summary: Get all comments for a task
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of comments
    post:
      tags:
        - comments
      summary: Create a new comment
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
      responses:
        '201':
          description: Comment created
    put:
      tags:
        - comments
      summary: Update a new comment
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
      responses:
        '200':
          description: Comment updated

  /api/v1/projects/{projectId}/tasks/{taskId}/attachments/:
    get:
      tags:
        - attachments
      summary: Get a file attachment
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
        - name: taskId
          in: path
          required: true
          schema:
            type: string
        - name: attachmentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: File attachment details
    post:
      tags:
        - attachments
      summary: Upload a file attachment
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: File uploaded

  /api/v1/projects/{projectId}/tasks/{taskId}/attachments/{attachmentId}/:
    delete:
      tags:
        - attachments
      summary: Delete a file attachment
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
        - name: taskId
          in: path
          required: true
          schema:
            type: string
        - name: attachmentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: File attachment deleted

  /api/v1/notifications/:
    get:
      tags:
        - notifications
      summary: Get all notifications for the user
      responses:
        '200':
          description: List of notifications

  /api/v1/notifications/{notificationId}/:
    put:
      tags:
        - notifications
      summary: Mark a notification as read
      parameters:
        - name: notificationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Notification marked as read

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        email:
          type: string
        password:
          type: string
        role:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Project:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
        created_by:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Task:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        status:
          type: string
        priority:
          type: string
        deadline:
          type: string
          format: date
        project:
          type: string
          format: uuid
        assigned_to:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Comment:
      type: object
      properties:
        id:
          type: string
          format: uuid
        content:
          type: string
        task:
          type: string
          format: uuid
        author:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time

    Attachment:
      type: object
      properties:
        id:
          type: string
          format: uuid
        file_path:
          type: string
        task:
          type: string
          format: uuid
        uploaded_by:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time

    Notification:
      type: object
      properties:
        id:
          type: string
          format: uuid
        content:
          type: string
        user:
          type: string
          format: uuid
        read:
          type: boolean
        created_at:
          type: string
          format: date-time
